apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserva-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reserva-service
  template:
    metadata:
      labels:
        app: reserva-service
    spec:
      containers:
        - name: reserva-service
          image: rafaelloureioc/reserva-service:latest
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: reserva-service
spec:
  selector:
    app: reserva-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
